ShopLinhKien/Areas/Admin/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopLinhKien.Common;
using ShopLinhKien.Models;

namespace ShopLinhKien.Areas.Admin.Controllers
{
    [CustomAuthorizeAttribute(RoleID = "ADMIN")]
    public class OrdersController : BaseController
    {
        private ShopLinhKienDbContext db = new ShopLinhKienDbContext();

        // GET: Admin/Orders
        public ActionResult Index()
        {
            var list = db.Orders.Where(m => m.status != 0).ToList();
            return View(list);
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.customer = db.Orders.Where(m => m.ID == id).First();
            var lisst = db.Orderdetails.Where(m => m.orderid == id).ToList();
            return View("Orderdetail", lisst);
        }
        //status
        public ActionResult Status(int id)
        {
            Morder morder = db.Orders.Find(id);
            morder.status = (morder.status == 1) ? 2 : 1;
            morder.updated_at = DateTime.Now;
            morder.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(morder).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Thay đổi trang thái thành công", "success");
            return RedirectToAction("Index");
        }
        //trash
        public ActionResult trash()
        {
            var list = db.Orders.Where(m => m.status == 0).ToList();
            return View("Trash", list);
        }
        public ActionResult Deltrash(int id)
        {
            Morder morder = db.Orders.Find(id);
            morder.status = 0;
            morder.updated_at = DateTime.Now;
            morder.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(morder).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Xóa thành công", "success");
            return RedirectToAction("Index");
        }

        public ActionResult Retrash(int id)
        {
            Morder morder = db.Orders.Find(id);
            morder.status = 2;
            morder.updated_at = DateTime.Now;
            morder.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(morder).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Khôi phục thành công", "success");
            return RedirectToAction("trash");
        }
        public ActionResult deleteTrash(int id)
        {
            Morder morder = db.Orders.Find(id);
            db.Orders.Remove(morder);
            db.SaveChanges();
            Message.set_flash("Đã xóa vĩnh viễn 1 Đơn hàng", "success");
            return RedirectToAction("trash");
        }
    }
}

ShopLinhKien/Areas/Admin/Views/Orders/Index.cshtml
@model IEnumerable<ShopLinhKien.Models.Morder>

@{
    /**/

    ViewBag.Title = "Order";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@Html.Partial("~/Areas/Admin/Views/Shared/_topMenu.cshtml")
@Html.Partial("~/Areas/Admin/Views/Shared/_leftMenu.cshtml")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row m-0">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Quản Lý Đơn Hàng</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Quản lý đơn hàng</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
  
    <section class="container-fluid ">
        <div class=" bg-white card  ">
            <div class="row justify-content-end">
                <div class="col-md-3">
                    <div class=" pt-1 mr-3 float-right">
                        <a class="text-white btn-sm btn-danger " href="~/admin/orders/trash">Thùng rác<i class="fas fa-trash"></i></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-9  w-100 ">
                    @Html.Partial("_MessgeAlert")
                </div>
                <div class="col-md-12 p-3">

                    <table id="myTable1" class="table  table-striped table-bordered dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Tên khách hàng</th>
                                <th>Ngày Tạo</th>
                                <th>Trang thái</th>
                                <th>Chi tiết</th>
                                <th>Hình thức thanh toán</th>
                                <th>Chức Năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                String dh1 = "Đã xác nhận";
                                String dh2 = "chờ xác nhận";
                            <tr>

                                <td><a class="card-link " href="@Url.Action("Detail", "Orders", new { id = item.ID })"> @Html.DisplayFor(modelItem => item.ID)</a></td>
                                <td class="font-weight-bold"> @Html.DisplayFor(modelItem => item.deliveryname)</td>
                                <td width="10%" style="font-size:14px;">@Html.DisplayFor(modelItem => item.created_ate) </td>
                                <td>
                                    @if (item.status == 1)
                                    {
                                        <p class="text-success"> @dh1</p>
                                    }
                                    else
                                    { <p class="text-danger"> @dh2</p>}
                                </td>

                                <td><a href="@Url.Action("Detail", "Orders", new { id = item.ID })">Xem Chi tiết</a></td>
                                <td>
                                    @item.deliveryPaymentMethod  @if (item.StatusPayment == 1)
                                                                {<span class="text-success">Đã thanh toán </span> }
                                                                else
                                                                {
                                                                    <span class="text-danger">Chưa thanh toán </span>
                                                                }
                                </td>
                                <td>
                                    @if (item.status == 1)
                                    {
                                        <a class="btn btn-sm btn-light text-success border a33" href="@Url.Action("Status", "Orders", new { id = item.ID })"> <i class="fas fa-toggle-on"></i> </a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-sm btn-light text-danger border a33" href="@Url.Action("Status", "Orders", new { id = item.ID })"> <i class="fas fa-toggle-off"></i> </a>
                                    }

                                    <a class="btn btn-sm btn-light text-danger border" href="@Url.Action("Deltrash", "Orders", new { id = item.ID })"> <i class="fas fa-trash-alt"></i></a>

                                    <a class="btn btn-sm btn-light text-orange border" href="@Url.Action("Deltrash", "Orders", new { id = item.ID })"> <i class="fas fa-ban "></i></a>
                                </td>
                            </tr>
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </section>
    <script>
        $("#order").addClass("active");
    </script>

ShopLinhKien/Areas/Admin/Views/Orders/Orderdetail.cshtml
@model IEnumerable<ShopLinhKien.Models.Mordersdetail>
@{
    var cus = @ViewBag.customer;

    ViewBag.Title = "Order";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@Html.Partial("~/Areas/Admin/Views/Shared/_topMenu.cshtml")
@Html.Partial("~/Areas/Admin/Views/Shared/_leftMenu.cshtml")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row m-0">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Chi tiết đơn hàng </h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Quản Lý Sản Phẩm</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <section class="pt-3 container">
        <div class="card">
            <div class="row">
                <div class="  col col-md-6 ">
                    <div class="card-header bg-secondary"><h3>Sản Phẩm</h3></div>
                    <table class="table table-striped table-bordered dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th width="20%">Mã</th>
                                <th width="20%">Tên</th>
                                <th width="20%">Giá</th>
                                <th width="20%">Số lượng</th>
                                <th width="20%">thành tiền</th>

                            </tr>
                        </thead>
                        <tbody>
                            @{
                                long sum = 0;
                            }
                            @foreach (var item in Model)
                            {
                                sum = sum + (long)item.amount;
                                <tr>
                                    <td> @item.ID</td>
                                    <td>@item.productid</td>
                                    @{ int sale = (int)item.priceSale;
                                        float price = (int)item.price - (int)item.price / 100 * (int)sale;}
                                    @if (sale > 0)
                                    {
                                        <td style="font-size:14px;">
                                            <strike> @item.price.ToString("N0") VND</strike><br />
                                            <span>@price.ToString("N0") VND</span>
                                        </td>
                                    }
                                    else
                                    {
                                        <td style="font-size:14px;"> @item.price.ToString("N0") VND</td>
                                    }

                                    <td>@item.quantity</td>
                                    <td>@item.amount.ToString("N0") VND</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="  border-bottom  col col-md-6 ">
                    <div class="card-header bg-secondary"><h3>Thông tin Khách hàng</h3></div>
                    <table class="table table-striped table-bordered dt-responsive nowrap">
                        <tbody>

                            <tr class="border-top">
                                <td class="pb-3 " style="font-weight: bold;">Tên: </td>
                                <td class="pb-3 pl-5">@cus.deliveryname</td>
                            </tr>
                            <tr class="border-top">
                                <td class="pb-3" style="font-weight: bold;">Địa chỉ:</td>
                                <td class="pb-3 pl-5">@cus.deliveryaddress</td>
                            </tr>
                            <tr class="border-top">
                                <td class="pb-3" style=" font-weight: bold;">Số điện thoại:</td>
                                <td class="pb-3 pl-5">@cus.deliveryphone</td>
                            </tr>
                            <tr class="border-top">
                                <td class="pb-3" style=" font-weight: bold;">Email: </td>
                                <td class="pb-3 pl-5">@cus.deliveryemail</td>
                            </tr>
                            <tr>
                                <td class="pb-3" style=" font-weight: bold;">Phương thức thanh toán: </td>
                                <td>
                                    @cus.deliveryPaymentMethod  @if (cus.StatusPayment == 1)
                                    {
                                        <span class="text-success">Đã thanh toán </span> }
                                    else
                                    {
                                        <span class="text-danger">Chưa thanh toán </span>
                                    }
                                </td>
                              
                            </tr>
                        <tr class="border-top">
                            <td class="pb-3" style=" font-weight: bold;">Thành tiền:</td>
                            <td class="pb-3 pl-5"><span class="text-cam font-weight-bold">@sum.ToString("N0") VND</span> <p class="text-danger"> Miễn phí vận chuyển</p></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <script>
        $("#order").addClass("active");
    </script>

ShopLinhKien/Areas/Admin/Views/Orders/Trash.cshtml
@model IEnumerable<ShopLinhKien.Models.Morder>

@{
    /**/

    ViewBag.Title = "Category";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@Html.Partial("~/Areas/Admin/Views/Shared/_topMenu.cshtml")
@Html.Partial("~/Areas/Admin/Views/Shared/_leftMenu.cshtml")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row m-0">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Thùng Rác Đơn Hàng</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Thùng rác đơn hàng</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->


  
    <section class="container-fluid ">
        <div class=" bg-white card  ">
            <div class="row justify-content-end">
                <div class="col-md-3">
                    <div class=" pt-2 ml-5 float-right mr-3">
                        <a class="text-white btn-sm btn-danger " href="~/admin/orders">Thoát</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-9  w-100 ">
                    @Html.Partial("_MessgeAlert")
                </div>
                <div class="col-md-12 p-3">

                    <table id="myTable" class="table  table-striped table-bordered dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Tên khách hàng</th>
                                <th>Ngày Tạo</th>
                                <th>Trang thái</th>
                                <th>Chi tiết</th>
                                <th>Chức Năng</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                String dh1 = "Đã xác nhận";
                                String dh2 = "chờ xác nhận";
                                <tr>

                                    <td><a class="text-cam font-weight-bold card-link " href=""> @Html.DisplayFor(modelItem => item.ID)</a></td>
                                    <td> @Html.DisplayFor(modelItem => item.deliveryname)</td>
                                    <td width="10%">@Html.DisplayFor(modelItem => item.created_ate) </td>
                                    <td>
                                        @if (item.status == 1)
                                        {
                                            <p class="text-success"> @dh1</p>
                                        }
                                        else
                                        { <p class="text-danger"> @dh2</p>}
                                    </td>

                                    <td class="text-cam "><a href="#">Xem Chi tiết</a></td>
                                    <td>
                                        <a class="btn btn-sm btn-light text-dark border" href="@Url.Action("Retrash", "Orders", new { id = item.ID })"> <i class="fas fa-undo"></i></a>
                                        <a class="btn btn-sm btn-light text-danger border" href="@Url.Action("deleteTrash", "Orders", new { id = item.ID })">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
    <script>
        $("#order").addClass("active");
    </script>